import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { redactNdjson, redactString, trimLog } from "./redact.js";

export const ISSUE_REPO = "conduit-harness/conduit";
const ISSUE_NEW_URL = `https://github.com/${ISSUE_REPO}/issues/new`;

export type ReportSummary = {
  conduitVersion: string;
  os: string;
  arch: string;
  nodeVersion: string;
  runnerKind: string | null;
  trackerKind: string | null;
  attempts: number;
  lastError: string | null;
};

export type ReportOptions = {
  domain?: string;
  type?: string;
  title?: string;
  homeDir?: string;
  workspaceRoot?: string;
  headLines?: number;
  tailLines?: number;
};

const DEFAULT_DOMAIN = "Core";
const DEFAULT_TYPE = "Bug";
const DEFAULT_TITLE = "Conduit run report";

export async function readPackageVersion(): Promise<string> {
  try {
    const here = path.dirname(fileURLToPath(import.meta.url));
    for (const candidate of [path.resolve(here, "../../package.json"), path.resolve(here, "../../../package.json")]) {
      if (existsSync(candidate)) {
        const raw = await readFile(candidate, "utf8");
        const parsed = JSON.parse(raw) as { version?: string };
        if (typeof parsed.version === "string") return parsed.version;
      }
    }
  } catch { /* fall through */ }
  return "unknown";
}

export function summarizeLog(ndjson: string, conduitVersion: string): ReportSummary {
  const summary: ReportSummary = {
    conduitVersion,
    os: `${os.platform()} ${os.release()}`,
    arch: os.arch(),
    nodeVersion: process.version,
    runnerKind: null,
    trackerKind: null,
    attempts: 0,
    lastError: null,
  };
  for (const line of ndjson.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    let record: Record<string, unknown>;
    try {
      const parsed = JSON.parse(trimmed) as unknown;
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) continue;
      record = parsed as Record<string, unknown>;
    } catch { continue; }
    if (typeof record.message === "string" && record.message === "agent starting") summary.attempts += 1;
    if (typeof record.tracker === "string" && summary.trackerKind === null) summary.trackerKind = record.tracker;
    if (typeof record.agent === "string" && summary.runnerKind === null) summary.runnerKind = record.agent;
    if (typeof record.error === "string" && record.error.length > 0) summary.lastError = record.error;
    if (record.level === "error" && typeof record.message === "string" && summary.lastError === null) summary.lastError = record.message;
  }
  return summary;
}

export function formatIssueBody(summary: ReportSummary, redactedLog: string, opts: ReportOptions = {}): string {
  const lines: string[] = [];
  lines.push("<!-- Generated by `conduit report`. The block below was redacted before display. Review and edit before submitting. -->");
  lines.push("");
  lines.push("### Run summary");
  lines.push("");
  lines.push(`- Conduit version: ${summary.conduitVersion}`);
  lines.push(`- OS: ${redactString(summary.os, opts)}`);
  lines.push(`- Arch: ${summary.arch}`);
  lines.push(`- Node: ${summary.nodeVersion}`);
  lines.push(`- Tracker: ${summary.trackerKind ?? "(unknown)"}`);
  lines.push(`- Runner: ${summary.runnerKind ?? "(unknown)"}`);
  lines.push(`- Attempts in last run: ${summary.attempts}`);
  if (summary.lastError) lines.push(`- Last error: ${redactString(summary.lastError, opts)}`);
  lines.push("");
  lines.push("### What happened");
  lines.push("");
  lines.push("<!-- Describe the unexpected behavior, what you expected, and any repro steps. -->");
  lines.push("");
  if (redactedLog.trim().length > 0) {
    lines.push("### Last run log (redacted)");
    lines.push("");
    lines.push("```");
    lines.push(redactedLog);
    lines.push("```");
  } else {
    lines.push("### Last run log");
    lines.push("");
    lines.push("_No `.conduit/logs/last-run.ndjson` was found — this report was filed without a log._");
  }
  return lines.join("\n");
}

export function buildIssueUrl(summary: ReportSummary, body: string, opts: ReportOptions = {}): string {
  const params = new URLSearchParams();
  params.set("template", "issue.yml");
  params.set("title", opts.title ?? DEFAULT_TITLE);
  params.set("domain", opts.domain ?? DEFAULT_DOMAIN);
  params.set("type", opts.type ?? DEFAULT_TYPE);
  params.set("description", body);
  void summary;
  return `${ISSUE_NEW_URL}?${params.toString()}`;
}

export function buildIssueTitle(summary: ReportSummary, opts: ReportOptions = {}): string {
  const domain = opts.domain ?? DEFAULT_DOMAIN;
  const subject = opts.title ?? (summary.lastError ? truncate(summary.lastError, 80) : DEFAULT_TITLE);
  return `${domain}: ${subject}`;
}

function truncate(text: string, max: number): string {
  const oneLine = text.replace(/\s+/g, " ").trim();
  return oneLine.length <= max ? oneLine : `${oneLine.slice(0, max - 1)}…`;
}

export async function readLastRunLog(logFilePath: string): Promise<{ path: string; content: string; exists: boolean }> {
  if (!existsSync(logFilePath)) return { path: logFilePath, content: "", exists: false };
  try {
    return { path: logFilePath, content: await readFile(logFilePath, "utf8"), exists: true };
  } catch {
    return { path: logFilePath, content: "", exists: false };
  }
}

export function defaultLogPath(logsRoot: string): string {
  return path.join(logsRoot, "last-run.ndjson");
}

export type BuildReportInput = {
  rawLog: string;
  logExists: boolean;
  conduitVersion: string;
  options?: ReportOptions;
};

export type BuiltReport = {
  summary: ReportSummary;
  body: string;
  title: string;
  url: string;
};

export function buildReport(input: BuildReportInput): BuiltReport {
  const opts = input.options ?? {};
  const redactedLog = input.logExists ? trimLog(redactNdjson(input.rawLog, opts), opts.headLines, opts.tailLines) : "";
  const summary = summarizeLog(input.logExists ? input.rawLog : "", input.conduitVersion);
  const body = formatIssueBody(summary, redactedLog, opts);
  const title = buildIssueTitle(summary, opts);
  const url = buildIssueUrl(summary, body, opts);
  return { summary, body, title, url };
}
